### ISSUE TITLE
When blog entry does not have any images then Featured and Recent posts will use main web site as image for post

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#294]
Steps:
1. Create new website using `dotnet new cloudscribe -D NoDb -S a -L true` (I did it few days ago for version 3.0)
2. Enable Show Recent Posts on Default Page and Show Featured Posts on Default Page
3. Create few blog entries without any images
4. Go to default page for that site.
5. You will see Recent Posts and Featured Posts with invalid image to blog entry left. 

I believe that issue happened because `ContentProcessor.ExtractFirstImageUrl` doesn't work correctly when `fallbackImageUrl` is empty string and empty string is used (`var defaultImageUrl = ""; //you can specify a default image`) in views by default

Perhaps this line:
`if (firstImageUrl == null) return fallbackImageUrl;`
should be changed to 
`if (string.IsNullOrWhiteSpace(ImageUrl)) return fallbackImageUrl;`

Also there is extra `if (item == null) return string.Empty;` that can be removed

**Comment by joeaudette** [comment]
Thanks for the bug report! I was able to reproduce the problem as described, and your diagnosis of a solution was correct.

If you update to all the latest cloudscribe nugets it should be fixed now.

**Comment by cheverdyukv** [comment]
Wow, that was fast! Thank you for that fix and for project in general! We appreciate you hard work.
