### ISSUE TITLE
Incorrect reference to rss on second site that uses folder tenancy

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#297]
I'm not 100% sure that this is bug, but on my second site:
www.mysite.com/second/blog 
I can see following in head tag:
`<link type="application/rss+xml" rel="alternate" title="Blog" href="/api/rss/">`
I think it is incorrect and it should be 
`<link type="application/rss+xml" rel="alternate" title="Blog" href="/second/api/rss/">`
because current one leads to rss of main site

**Comment by joeaudette** [comment]
Thanks for the bug report, This is fixed if you update to the newest nugets.

**Comment by cheverdyukv** [comment]
Fixed now. Thank you again!
