### ISSUE TITLE
 sql about mysql  is wrong 

### ISSUE THREAD

**Issue by lucksuper** [cloudscribe/cloudscribe.SimpleContent#299]
ALTER TABLE `cs_Page` ADD DEFAULT FALSE FOR `ShowPubDate`;

mysql

**Comment by joeaudette** [comment]
not a clear question.

If you think there is a bug please provide steps to produce the problem, expected result actual result.

maybe in early versions of the mysql ef layer we were setting a default of false for that in the dbcontext, but that was later corrected and newer migrations would remove the db default. The default comes from the model class.
