### ISSUE TITLE
New version has add, unpublish and edit button too close to each other

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#310]
See image ![image](https://user-images.githubusercontent.com/18220536/43114805-a2a1f7ea-8eb5-11e8-972b-7e0426c6ebf9.png)
It is Firefox  61.0.1

**Comment by joeaudette** [comment]
it is positioned correctly in the custom1 theme that ships in the template. I don't think it is possible to make it perfect in every unknown theme, so you should just adjust it in your css as needed for your theme

    #unpublishPageLink {
        position: absolute;
        top: 160px!important;
        right: 0px!important
    }

    #unpublishPostLink {
        position: absolute;
        top: 130px!important;
        right: 0px!important;
    }

**Comment by cheverdyukv** [comment]
Fixed by switching to proper theme instead of using default one
