### ISSUE TITLE
No icon for Content History in Admin menu

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#317]
I'm not sure what icon would be suitable, but the absence of an icon is out of kilter with the other pages/functions:
![image](https://user-images.githubusercontent.com/10574730/43272191-3fef0a14-90f1-11e8-8aa6-c55739867bd0.png)

**Comment by joeaudette** [comment]
I've published an updated project template and added the updated css so it should work out of the box now if you update the vs project template
