### ISSUE TITLE
Content History "View" links open pages in new window - intended?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#318]
This was surprising and feels out of line with other cloudscribe behaviour, and personally I like links to open in same window unless I willingly use the browser's capabilities to do otherwise.

**Comment by joeaudette** [comment]
yes it was intended because in actual use if you are looking for a version to restore you often need to compare several history items to find the one you are looking for and opening them in new tabs facilitates that.

**Comment by CrispinF** [comment]
OK, seems fair enough and useful. Might be good to give the link/button an accessible tooltip telling the user the result will open in a new window?

**Comment by joeaudette** [comment]
I've added a title/tooltip indicating it will open in a new window. nuget published, it may take a few minutes before it is available
