### ISSUE TITLE
Templates - no content when publish later from the start

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe.SimpleContent#322]
I created a page based on the new link list template added an image (from server), description and link.  Selected publish later, the page then show a message like so:

![image](https://user-images.githubusercontent.com/10956017/43310939-f2202bfc-9180-11e8-8870-cf5ba669df82.png)

But when the time came the page had no content and when I went to edit the content, the content I added is gone.

Not a biggy but the calendar appears partially off the bottom of the screen, is there a setting to get it to appear above the input box if it will otherwise appear off screen at the bottom?

**Comment by StewartBellamy** [comment]
On this same page if I now add an image/link/description and press save draft or publish now the content always disappears.  In the version history I have 4 versions now and they are all empty.

**Comment by StewartBellamy** [comment]
Ok I see what I've done.  You are supposed to click 'add link' before save/publish.  I'm not sure this will be entirely obvious to all levels of user, especially me!  Is it clear that 'add link' is for adding the current one rather than a new one especially as when you click it you get to add details for a new link.

**Comment by joeaudette** [comment]
I've added separate fieldsets and legends around the current link items and the add new link item form fields to make it clearer that you need to click the add link button.

I've updated the datepicker to auto layout so it should not go below the bottom of the screen.

These fixes require all the latest cloudscribe nugets

**Comment by StewartBellamy** [comment]
Datepicker position ok now, the fieldsets and legends help make it clearer too.
