### ISSUE TITLE
Templates - loss of last published version

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe.SimpleContent#323]
Steps to reproduce:

1. Add new page based on link list, add one image with title & link url, click add link!, then 'publish now'
2. Add top content and 'publish now'
3. Add bottom content and 'publish now'
4. Now go to version history, view the top item which is the page with an image and top content and restore this version to the editor, click publish now

The correct page content is now published.  But we have lost the last published version of the page, i.e. the one with top, image and bottom content.  I'm not sure if this is correct behaviour or not, but you have lost a version of content that was previously published.

**Comment by joeaudette** [comment]
thanks for the bug report, this is fixed in the latest nugets

**Comment by joeaudette** [comment]
@StewartBellamy I believe this is fixed, can we close this issue?

**Comment by StewartBellamy** [comment]
Tested and confirmed fixed.
