### ISSUE TITLE
Content edit history - delete

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe.SimpleContent#324]
Go to the content edit history for a given page and delete one of the items.  When the page reloads you are taken to a content edit history view for all content.  Would it be a better user experience if you were taken back to the content edit history for the page that you were editing?

**Comment by joeaudette** [comment]
this is fixed in the latest nugets

**Comment by StewartBellamy** [comment]
Confirmed fixed.
