### ISSUE TITLE
Content edit history - published date

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe.SimpleContent#326]
Might it be useful to show the published date on the content edit history list?

And also on the individual content history view page?

![image](https://user-images.githubusercontent.com/10956017/43316382-1d59c3ea-9191-11e8-9aa1-4fe3bc2e0c5c.png)

**Comment by joeaudette** [comment]
I've added pub date to the history grind in the latest nugets

**Comment by StewartBellamy** [comment]
Agree.  Published date now appearing on the content edit history view.
