### ISSUE TITLE
Templates - can they output content into the page head section?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#330]
Often pages want specific content in the head section (relating to the content on the page), in a wide variety of metadata schemas (Dublin Core, open graph, Twitter cards, etc).
Is there any way of outputting Templated page data into the head section?

**Comment by joeaudette** [comment]
Advanced meta data is a completely separate problem that is not solved by content templates and is not specific to templated content. 

I have some ideas about how to implement advanced meta data and would be happy to discuss it, but if you are interested in discussing it please close this issue and open a new one with "advanced meta data" in the title and not "Templates"

**Comment by joeaudette** [comment]
I will go ahead and mention here that twitter cards and some facebook opengraph meta data is already implemented for pages and posts.

Those can be done with the meta description, page title, and the first image which is auto extracted from the content.
Twitter cards have also twitter:site and twitter:creator, at the moment these come from Administration > Content Settings

You can see the current logic in the [pagemetaview](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Page/MetaPartial.cshtml) and in the [postmetaview](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Blog/BlogMetaPartial.cshtml)

**Comment by CrispinF** [comment]
Hi Joe, I'd say that they are overlapping issues rather than entirely separate ;-P but it's great to hear that you have some ideas for implementing advanced metadata, and that some simple metadata scenarios are already implemented. So yes, happy to close this one and open a new one...
