### ISSUE TITLE
No coloring info for code snippets in blog posts

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#335]
Hi

I found that when I edit blog post and insert blog snippets I can see some syntax highlighting like this:
![image](https://user-images.githubusercontent.com/18220536/44241080-8850a700-a176-11e8-944e-3ace92f6b4a4.png)
but when I publish post it looks like that:
![image](https://user-images.githubusercontent.com/18220536/44241093-99011d00-a176-11e8-9aee-7a5a11ce606f.png)

Is it suppose to be like that or something broken in my setup?

Thanks.

**Comment by joeaudette** [comment]
This is fixed in the latest nugets.

**Comment by cheverdyukv** [comment]
It looks better but it looks different from colors when I edit:
![image](https://user-images.githubusercontent.com/18220536/44370470-34ec9a80-a48f-11e8-8eef-016e5f1cc5d3.png)

It is atelier-forest.light theme and when I edit it uses default theme. Is there any way to sync or even better to change it somehow?
I found this article: https://www.cloudscribe.com/docs/customizing-the-editor
but I think it is outdated as highlighting works by default

**Comment by joeaudette** [comment]
Yes I added it by default for this issue.

Will you be satisfied if I make the editor use atelier-forest.light theme by default? or should I make simplecontent use the default theme when rendering?

In either case you can override the [StylePartial](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Page/StylePartial.cshtml) for pages and [BlogStylePartial](https://github.com/cloudscribe/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.CompiledViews.Bootstrap4/Views/Blog/BlogStylePartial.cshtml) for posts to change the css theme file used.

And you can override the ckeditor config file to change it in the editor. Currently it is not specified so it uses the default theme.

**Comment by cheverdyukv** [comment]
Hi Joe

Ideally I would like to change ckeditor config file but  BlogStylePartial allows me to do the same so I can live with that. The only downside of that solution that from now on I have to track changes in BlogStylePartial in case it will be changed

**Comment by joeaudette** [comment]
Not that I see it as a big burden to override views for customization, but if I make the editor use the atelier-forest.light theme by default will you still be overriding it? Or do you think I should make simplecontent use the default theme which is already used by the editor?

**Comment by cheverdyukv** [comment]
To be honest atelier-forest.light is hard to read. I did overwrite BlogStylePartial and used Visual Studio theme. Difference between view and edit do not bother me much. But default theme is better that atelier-forest.light to my eyes. The best solution would ability to edit via site preference or global preferences but I think it is too much work.

**Comment by joeaudette** [comment]
I've change simplecontent to use the default theme, and published updated nugets.

Satisfied to close this?

**Comment by cheverdyukv** [comment]
Yep. Thank you for your help!
