### ISSUE TITLE
Error in Metaweblog

### ISSUE THREAD

**Issue by jasongaylord** [cloudscribe/cloudscribe.SimpleContent#346]
When trying to get the recent posts for my blog, I'm receiving the following error:

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware /api/metaweblog 
An unhandled exception has occurred while executing the request.&#xD;&#xA;System.InvalidCastException: Unable to cast object of type &#x27;cloudscribe.SimpleContent.Storage.EFCore.Models.PostEntity&#x27; to type &#x27;cloudscribe.SimpleContent.Models.Post&#x27;.&#xD;&#xA; at cloudscribe.SimpleContent.MetaWeblog.MetaWeblogService.GetRecentPosts(String blogId, String userName, String password, Int32 numberOfPosts, CancellationToken cancellationToken)&#xD;&#xA; at cloudscribe.MetaWeblog.MetaWeblogRequestProcessor.ProcessRequest(MetaWeblogRequest input, MetaWeblogSecurityResult permission, CancellationToken cancellationToken)&#xD;&#xA; at cloudscribe.MetaWeblog.Controllers.MetaWeblogController.Index()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)&#xD;&#xA; at System.Threading.Tasks.ValueTask`1.get_Result()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()&#xD;&#xA; at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA; at cloudscribe.Core.Web.Middleware.EnforceSiteRulesMiddleware.Invoke(HttpContext context, SiteContext currentSite, IOptions`1 multiTenantOptionsAccessor, IUserContextResolver userResolver, IAccountService accountService)&#xD;&#xA; at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)&#xD;&#xA; at SaasKit.Multitenancy.Internal.TenantPipelineMiddleware`1.Invoke(HttpContext context)&#xD;&#xA; at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.Invoke(HttpContext context, ITenantResolver`1 tenantResolver)&#xD;&#xA; at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA; at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by joeaudette** [comment]
Thanks for the bug report. Looking into this now.

**Comment by joeaudette** [comment]
This is now fixed and I've published a new nuget, it might be a little while before the nuget is indexed and available https://www.nuget.org/packages/cloudscribe.SimpleContent.MetaWeblog/4.0.3

**Comment by joeaudette** [comment]
If you could update to the latest nugets and verify the fix then we can close this one.
