### ISSUE TITLE
Support future publish date

### ISSUE THREAD

**Issue by jasongaylord** [cloudscribe/cloudscribe.SimpleContent#356]
Currently, SimpleContent assumes two states: draft posts and publish now. In the `NewPost` method of `cloudscribe.SimpleContent.MetaWeblogService`, if publish == true, the pubDate is reset to DateTime.UtcNow. The problem is that we are overriding the publish date with now as opposed to using the value being passed in.

My proposed solution is the following: Update this method to continue setting IsPublished to true, but not listing it if using a role other than an administrator or blog editor. So, RSS and typical lists won't have it until the time is met. I may need a list of roles that should have this view. If there's already a role checker built in, please let me know.

Generally speaking, we shouldn't worry about date checking as a blog editor should be allowed to back date a post.

@joeaudette If you agree, I'll update accordingly.

**Comment by joeaudette** [comment]
@jasongaylord I see the problem and fixing it now, will publish updated nugets shortly.

Recently we introduced content history and we changed the implementation of draft vs publish and at that time we did not correctly update the metaweblog service to account for the changes.

I also found another bug when using NoDb, from the web we are using the slug as the id because that makes nicer file names on disk. But with posts created in OLW, it sets the post id to a guid, and it expects to be able to retrieve it using that guid. So I had to fix the NoDb storage code to leave the id alone if it is already populated instead of assuming we need to populate it when creating new posts.

**Comment by jasongaylord** [comment]
Thanks @joeaudette! Let me know if you need my help and/or testing this out.

**Comment by joeaudette** [comment]
@jasongaylord I've just published updated nugets, if you can test and confirm the fix that would be great.

I did see one anomaly that I haven't figured out yet if you care to look into it. In olw when I click File > Open Recent Post (not clicking the ones shown at hover time so it opens the dialog shown below), if I look at the list of pages, they all appear as if they have no title, but if you load one for editing they have a title, and stepping through the code the title is being set on the structs we pass in the list. I'm not sure why that is happening unless our structs are not in the expected format for pages.

![olw-pages-no-title2018-10-23_14-56-12](https://user-images.githubusercontent.com/101627/47386034-a5a37380-d6d9-11e8-8335-fe4eb1a9f240.jpg)

It only happens for pages, not posts. If you care to look into it please feel free.

**Comment by joeaudette** [comment]
nevermind, I fixed the page list problem, it was a bug in the main metaweblog package. I compared to an older implementation and figured out what was missing. Latest nugets should be all good.

**Comment by jasongaylord** [comment]
@joeaudette It's working... sort of. It does post as a draft, but doesn't take the time zone into consideration. So, I've posted something with a 3pm EST post date and when I log in, I can see the post would have posted to 7pm EST instead. Is there something assuming that the time coming in has been set as UTC instead of an appropriate time zone?

**Comment by joeaudette** [comment]
@jasongaylord we store all dates as UTC and we convert them to a time zone for display. For that to work you need to set the correct time zone for you user account, ie login, click the "hello" link which goes to account settings and there you can specify your time zone. If a user does not have a time zone specified then it falls back to the time zone set in site settings.

So when you post with olw, it assumes the posted date is in your time zone and based on that timezone it converts it to utc. Then at render time it converts back to either the user's time zone or the site default time zone for unauthenticated users.

So as long as the machine where you use olw has the time zone the same as your cloudscribe user account and as long as the system clock on the server is correct, the datetime should be handled correctly.

**Comment by joeaudette** [comment]
Note also that the default date format in Administration > Content Settings doesn't include the time, it has MMMM d. yyyy

If you change that to f for full date time you should see the time. In my testing a post from olw with pub date time set in olw displays the correct time on the web for my time zone which is also eastern time.

**Comment by jasongaylord** [comment]
And I checked the Azure App Service time and the server is correct as shown from the Server UTC in the CloudScribe system output:
![server-utc](https://user-images.githubusercontent.com/1865758/47500357-984ccd00-d830-11e8-83a6-280eb1b3c378.png)
So, I decided to create a quick test post in OLW and publish with a future time like so:
![post-in-olw](https://user-images.githubusercontent.com/1865758/47500381-a7337f80-d830-11e8-81dc-5f034e9547f8.png)
But when I visit that post in the system, it shows a different time that it will be published:
![post-in-cloudscribe](https://user-images.githubusercontent.com/1865758/47500432-cf22e300-d830-11e8-8eca-adcd9b441274.png)
Another quick thing I noted is that the items posted in the future do not show up in Content History but only in the blog listing if logged in as an admin:

**Comment by joeaudette** [comment]
@jasongaylord content history is only a history of edits, if you make a new post nothing will be added to history, only if you edit a post then the previous version is saved as history before the new edit is saved as the current version. The purpose of content history is not to lose data and to be able to restore a previous version. Also when draft edits are made the history of draft edits is purged when it gets published, only published edits are kept long term.

I can only guess the time zone issue is an azure issue. Testing locally:

OLW pub date:

![olw-pubtime](https://user-images.githubusercontent.com/101627/47501036-66d50100-d832-11e8-8da5-10cce0a7bf65.jpg)

web pub date:

![web-pub-time](https://user-images.githubusercontent.com/101627/47501041-72282c80-d832-11e8-9974-7473971f7477.jpg)

**Comment by jasongaylord** [comment]
@joeaudette I double checked. The app service is running as UTC instead of EST. I've got it figured out. I'll blog about it.

**Comment by joeaudette** [comment]
@jasongaylord glad to hear you got it working, had me worried there for a second. I just deployed the latest to cloudscribe.com and then tested a future post and it worked correctly for me there. Just wanted to make sure it worked using a remote server. cloudscribe.com is on a traditional vm with iis.

**Comment by jasongaylord** [comment]
@joeaudette No problem. Thanks for dealing with my insanity. My best guess is that OLW isn't passing over the time zone so while CloudScribe is handling it properly, it doesn't know what time zone to use for the value being passed in. I blogged about it [here](https://www.jasongaylord.com/blog/tip-changing-an-azure-app-service-time-zone). I usually blog about the things I tend to forget about because I use them only once a year or so. :)

**Comment by joeaudette** [comment]
@jasongaylord nice to see your blog running on cloudscribe, good job with the design too!
