### ISSUE TITLE
CMS tool icons crashing into each other with a BS4 theme

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#381]
Using VS Template for a Simple Content site, with the standard BS4 themes e.g. darkly, the "Unpublish" icon is preventing easy use of New Page and Edit:
![image](https://user-images.githubusercontent.com/10574730/52526167-b4279200-2cac-11e9-8cb3-751dec8c5494.png)

**Comment by joeaudette** [comment]
Thanks for the bug report!
This is now fixed and updated project template published.
