### ISSUE TITLE
Missing setting SiteUploadFilesRootFolderName from doc page on Multi Tenant

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#383]
https://www.cloudscribe.com/docs/multi-tenant-support 
Should this page now include and explain the "SiteUploadFilesRootFolderName": "siteuploadfiles" setting? This setting appears in a new multi-tenant site created using the template. Maybe useful to explain the precise purpose of this and "SiteFilesFolderName": "sitefiles", and when/why you'd have them the same or different. Thanks.

**Comment by joeaudette** [comment]
I've updated the documentation to add the missing setting explain the reasoning and purpose. Closing this but feel free to re-open if you don't think it is explained well.

**Comment by CrispinF** [comment]
Perfect.

Sent from my phone.

________________________________
