### ISSUE TITLE
Child site with blog to use different AboutPartial.cshtml (or populate this in Settings?)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#385]
If I want the sidebar "About" to be different on a blog in a child site, I imagine I can override the view but where do I put this file?  All the views seem to be compiled.

Alternatively, and maybe this is a feature request, could this bit of content be authored within Content Settings?  Or could it simply/optionally publish the Blog Description that can already be edited in Content Settings?

**Comment by CrispinF** [comment]
OK got it: in VS put it in \sitefiles\s2\Views\Blog\AboutPartial.cshtml and publish.

Would still be nice to be able to do this within the admin UI.

**Comment by joeaudette** [comment]
I'm open to making the about an editable part of content settings but could only make it a priority with sponsorship.

The easiest way right now is for child sites to use separate themes and override the view in the theme.

However if you are sharing a theme across the child sites you can also create a per tenant views folder separate from the themes, ie if the site aliasid is s2 then create a folder

/sitesfiles/s2/Views/Blog/About.cshtml

as opposed to

/sitesfiles/s2/themes/[themname]/Views/Blog/About.cshtml

that way you can still override the view per tenant no matter which theme is used. But keep in mind if the view file exists in the theme it will be used from there as that is a more specific override.

**Comment by CrispinF** [comment]
I have this working, if I create the override in development environment.  
Just wondering: should it be possible to drop an override into the published site?  I find when I add \sitefiles\s2\Views\Blog\AboutPartial.cshtml we get an error on loading the blog:
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware /music/blog 
An unhandled exception has occurred while executing the request.&#xD;&#xA;System.InvalidOperationException: Cannot find compilation library location for package …

It's clearly seeing and trying to use the override, but for some reason it's not working.

**Comment by joeaudette** [comment]
It would be possible by changing some settings in .csproj to compile views on demand and include needed dependencies for view compilation at runtime but the default settings are designed to use pre-compiled views and I would not recommend changing that.

**Comment by joeaudette** [comment]
fyi, I've gone ahead and made about me an editable part of content settings. I've published update nugets and I removed the About.cshtml from the project template since the only reason it was included as a local view in the template was to make it easy to edit the view in the project.
So for existing projects if you update the nugets then you probably want to delete that local view since it doesn't match the new one.
Also note I did not update this for bootstrap3, so keep the about partial for bootstrap3 projects.

**Comment by CrispinF** [comment]
@joeaudette just updated nugets, and now I get this:

A database operation failed while processing the request.
SqlException: Invalid column name 'AboutContent'. 

There are pending model changes for SimpleContentDbContext
In Visual Studio, use the Package Manager Console to scaffold a new migration for these changes and apply them to the database:
PM> Add-Migration [migration name] 
PM> Update-Database 
Alternatively, you can scaffold a new migration and apply it from a command prompt at your project directory:
> dotnet ef migrations add [migration name] 
> dotnet ef database update 

Something missing?

**Comment by joeaudette** [comment]
doh! my bad I somehow forgot to publish the data nugets. Just published them, might be a little time before they are indexed and ready.

**Comment by CrispinF** [comment]
@joeaudette working now thanks.  Also that sticky Register link now resolved with the updates.

**Comment by CrispinF** [comment]
@joeaudette a small follow-up issue. The AboutContent being editable from Content Settings is fantastic, but there's still this big "About me" heading. That heading is not appropriate for my blogs, which are not "About Me"!  Just changing this to "About" would work for mine.   I think I've seen in the code this is a localisable resource (with very different default text), but... wouldn't changing that apply to all my blogs, or can the resx be per site? And right now a search is failing to find "About me" in the entire solution!? Is this baked into a nuget?

**Comment by joeaudette** [comment]
@CrispinF the same thing occurred to me after using it. I've published updated nugets with the default as "About" but now the heading is also editable and there is a toggle to show or hide the about box completely in project settings so no-one needs to override the view if they don't want it at all.

**Comment by CrispinF** [comment]
That sounds great, I'll give it a try later.
