### ISSUE TITLE
After switching off "Allow New Registrations" the Register link is visible until site re-started

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#388]
I guess this is cached and changing the setting doesn't flush the cache until app pool recycled (or stop and start the site in VS)?
Had me rather confused though - wondering how my multi-tenant site might be affecting things, etc!

**Comment by joeaudette** [comment]
This isn't a simplecontent issue, but in any case I cannot reproduce it with latest nugets.

If the problem persists please log an issue in the [cloudscribe core repo](https://github.com/cloudscribe/cloudscribe/issues) with more information about steps to produce the problem.
