### ISSUE TITLE
How hide "0 comments" when a blog doesn't support commenting?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#391]
I have a blog where I don't want to support any commenting. 
In settings I set "Days To Comment" = 0.  No Disqus installed.

But I still see "0 comments" on every post, and this isn't in any easy element to hide with css (no ID).
Am I missing something?
If I'm not, could it be made that this doesn't appear when commenting is not permitted?

**Comment by joeaudette** [comment]
Thanks for the bug report. Just published updated bootstrap4 views nuget to solve this.

**Comment by CrispinF** [comment]
@joeaudette how do I pick up this fix?  I've updated nugets, but no change, and I can't see the fixed file in my solution.

**Comment by CrispinF** [comment]
@joeaudette ignore that - I am seeing the fix in a blog where I've configured it for no comments!

**Comment by joeaudette** [comment]
If you have a project overriding views then you would need to copy the fix from the latest views into your local views.
