### ISSUE TITLE
Should categories really be case sensitive?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#403]
I'm thinking probably they should not, but they seem to be, e.g.
![image](https://user-images.githubusercontent.com/10574730/53304650-a9a1f680-386f-11e9-80eb-fe074d8c00e6.png)

**Comment by joeaudette** [comment]
I recommend always use lower case categories.

The category list uses Group By in EFCore/Linq, 

I don't think we can make that case insensitive, could ToLower in the group by but that creates strings which is best to avoid as strings are immutable and accumulate memory usage until they get garbage collected. 

Also if we did that then its ambiguous which one would be rendered in the list the lower version or the one with capital letter.

**Comment by CrispinF** [comment]
@joeaudette I'm suddenly feeling some deja vu here, like maybe we discussed it before?
One solution would be to push categories to lowercase on entry, but that might felt to be undesirable in some sites. Did you even already implement this with a config setting to enable/disable this behaviour? If not, maybe this was a dream, but how about it!?

**Comment by joeaudette** [comment]
@CrispinF I was thinking the same thing. Checked and yes it is configurable, you can add this section in appsettings. Shown with default values:

    "BlogEditOptions" : {
     "ForceLowerCaseCategories": false,
     "AllowMarkdown":true,
     "HideUnpublishButton": false
     }

I think we decided to make the default false since users can easily see the problem and just go fix the posts to make them consistent if they don't want all lower case. I think early versions were forcing lower case.

**Comment by joeaudette** [comment]
I will add that in the project template for next release to make it more discover-able.

**Comment by joeaudette** [comment]
happy to close this?

**Comment by CrispinF** [comment]
Yes, thanks Joe, closing
