### ISSUE TITLE
Post Visitor View Count  :Enhancement

### ISSUE THREAD

**Issue by abomadi** [cloudscribe/cloudscribe.SimpleContent#405]
Adding post view is a good feature allows the site owners / visitor how interesting is the post / page.

**Comment by joeaudette** [comment]
why not just use google analytics? Not sure I like the idea to update data on get requests.

**Comment by abomadi** [comment]
Google analytics to give insights for site owners, however calculating views on posts can add different features like most viewed articles, and encourage other users to read more articles if it took their attention

Please excuse any tpyos as it was sent from my iPhone

**Comment by joeaudette** [comment]
I think something like that could be built as a separate feature. I don't think it is something I want to bake into simplecontent.

A generic solution would have a model like:

    public class UrlViews
    {
        public string RequestPath { get; set; }
        public int ViewCount { get; set; }
     }

then middleware could be written to create or update that on every request. It could be used for any feature and would not be limited to pages and posts. 

Then a taghelper could be written to show the viewcount for the current url/request path and that could be added into a view to show the count to users.

A more elaborate version could capture a row for every view with ipaddress and userid if authenticated.

I think a generic solution would be better than implementing that per feature. But I'm not planning to do that myself soon, just giving an idea how it could be done.

**Comment by abomadi** [comment]
@joeaudette yeah nice idea, i will try figure this out, Thanks
