### ISSUE TITLE
[I was able to create a] Duplicated blog post (which causes error)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#410]
[Much of this overridden by later comments] 
OK here's a strange one... I create a blog post in one operation, setting a past date and using "Publish Later" (a technique I'm using to transfer older posts from another site and preserve their publication date). I'm pretty sure I didn't click anything twice, but on saving I immediately got an error, and here's the result, two identical posts:
![image](https://user-images.githubusercontent.com/10574730/53686094-fdeb2180-3d1a-11e9-9fa9-39bed1b8438a.png)

These three errors in the log:

18:42:10 Error 51.9.169.xxx Microsoft.EntityFrameworkCore.Query /blog/virgoan-responses-now-available
An exception occurred in the database while iterating the results of a query for context type &#x27;cloudscribe.SimpleContent.Storage.EFCore.MSSQL.SimpleContentDbContext&#x27;.&#xD;&#xA;System.InvalidOperationException: Source sequence contains more than one element.&#xD;&#xA; at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)&#xD;&#xA;System.InvalidOperationException: Source sequence contains more than one element.&#xD;&#xA; at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)

02/03/2019 18:42:10 Error 51.9.169.xxx Microsoft.EntityFrameworkCore.Query /blog/virgoan-responses-now-available
An exception occurred in the database while iterating the results of a query for context type &#x27;cloudscribe.SimpleContent.Storage.EFCore.MSSQL.SimpleContentDbContext&#x27;.&#xD;&#xA;System.InvalidOperationException: Source sequence contains more than one element.&#xD;&#xA; at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)&#xD;&#xA;System.InvalidOperationException: Source sequence contains more than one element.&#xD;&#xA; at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)

02/03/2019 18:42:10 Error 51.9.169.xxx Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware /blog/virgoan-responses-now-available
An unhandled exception has occurred while executing the request.&#xD;&#xA;System.InvalidOperationException: Source sequence contains more than one element.&#xD;&#xA; at System.Linq.AsyncEnumerable.SingleOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)&#xD;&#xA; at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)&#xD;&#xA; at cloudscribe.SimpleContent.Storage.EFCore.PostQueries.GetPostBySlug(String blogId, String slug, CancellationToken cancellationToken)&#xD;&#xA; at cloudscribe.SimpleContent.Services.BlogService.GetPostBySlug(String slug, CancellationToken cancellationToken)&#xD;&#xA; at cloudscribe.SimpleContent.Web.Mvc.Controllers.BlogController.Post(CancellationToken cancellationToken, Int32 year, Int32 month, Int32 day, String slug, Boolean showDraft, Nullable`1 historyId)&#xD;&#xA; at cloudscribe.SimpleContent.Web.Mvc.Controllers.BlogController.Post(CancellationToken cancellationToken, String slug, Boolean showDraft, Nullable`1 historyId)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()&#xD;&#xA; at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()&#xD;&#xA; at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)&#xD;&#xA; at cloudscribe.Core.Web.Middleware.EnforceSiteRulesMiddleware.Invoke(HttpContext context, SiteContext currentSite, IOptions`1 multiTenantOptionsAccessor, IUserContextResolver userResolver, IAccountService accountService)&#xD;&#xA; at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)&#xD;&#xA; at SaasKit.Multitenancy.Internal.TenantPipelineMiddleware`1.Invoke(HttpContext context)&#xD;&#xA; at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.Invoke(HttpContext context, ITenantResolver`1 tenantResolver)&#xD;&#xA; at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)&#xD;&#xA; at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

Now I can't get rid of the duplicate through the UI, as I cannot get to the post. I will remove it in the database.

And when I said above that I created this in one operation, now I have a bit of doubt. On one post I transferred I accidentally published "now" then went back and used "Publish Later" with a specified date - it could have been this one. But I'm sure I used that sequence before without trouble.

**Comment by CrispinF** [comment]
Ah I just spotted in my screenshot - one of the posts has the "music" tag and the other doesn't.

**Comment by CrispinF** [comment]
OK update!  Turns out I'd already posted/transferred this post some days ago.  So the issue changes dramatically: I was not prevented from creating a duplicate slug, which in turn caused the error.

**Comment by joeaudette** [comment]
I'm not clear on steps to reproduce this and am doubtful this issue happens in the latest nugets. I [fixed an issue with slugs on Feb 13](https://github.com/cloudscribe/cloudscribe.SimpleContent/commit/121cc5b7d7c4d063a8929f7f3efaf4de12d668b5#diff-e506bf441b37c4218351fcffac333f80). Now it should keep appending - to the slug until it finds one that isn't in use. Actually before I think it was just failing to populate the slug if it was already in use.

Are you overriding a view to manually enter the slug because the default edit view doesn't show the slug and it is generated from the title.

**Comment by CrispinF** [comment]
No, no overrides, and very recent nugets. I'll see if I can replicate.

**Comment by CrispinF** [comment]
Yes, easy to replicate. Create new post with same title as an existing one, set a publish date, click "Publish Later" > bang.

**Comment by joeaudette** [comment]
Thanks! I was able to produce the problem and fix it.  New nuget published https://www.nuget.org/packages/cloudscribe.SimpleContent.Web/4.0.29
