### ISSUE TITLE
Sitemap to include lastmod element for pages

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#413]
For posts the date is included e.g. 
```xml
<url>
<loc>https://peter-tranchell.uk/blog/analysis-by-peter-marchbank-part-3-music-of-the-1950s</loc>
<lastmod>2019-03-02T16:15:46+00:00</lastmod>
</url>
```
but for pages we get no date. 
I know it's optional in the spec, and we don't really know how search engines will use it, but if it's sensible to include it for posts wouldn't the same apply for pages?   I'd guess it might possibly be a thing SEs use to judge a site for reliability and quality of content.

**Comment by joeaudette** [comment]
didn't know that. nice!

**Comment by joeaudette** [comment]
this is now fixed in the latest nugets. I updated the navigation node with a nullable LastModified time and then updated the pagestreebuilder to populate it so that we can still use the sitemap from navigation for pages.
