### ISSUE TITLE
a better localization story

### ISSUE THREAD

**Issue by joeaudette** [cloudscribe/cloudscribe.SimpleContent#415]
Currently when SimpleContent is used with cloudscribe Core, the project settings for SimpleContent uses the siteid as the project id. This is how content is separated per site. When used with cloudscribe core folder tenants and related sites mode it can also be used to support localization of content. A folder tenant can be created for specific languages like /fr /it etc as folders that correspond to additional sites and therefore conveniently correspond to separate content projects so that there can be a project per language. Using related sites mode all the tenants share the same users and roles so with folder tenants it really just seems like a single site with separate content per language.

However, the above solution while good for some scenarios is not good for saas solutions. Often saas solutions want to use hostname multi-tenancy with cloudscribe core, but then they have no way to have separate content projects per language because hostname multi-tenancy is mutually exclusive to folder based multi-tenancy, you cannot use both in a single installation. So another solution that allows localization would be nice.

As mentioned above how it works today is the projectid which is a string corresponds to the siteid which is a guid. It is fortunate that projectid is a string and not a guid because that means we are not limited to using just a guid to identify a content project. So it could be possible to have multiple content projects per site to allow a content project per language per site. The default language could continue to just use the siteid for the projectid, but for other supported languages we could use siteid-langcode for the project id. We really only want one projectsettings per site but only want different projectids per language so that content can be retrieved by the language as needed. Fortunately since simplecontent was not designed to follow strict relational rules about data, ie it is NoSql friendly and doesn't use foreign keys that would get in the way of this idea. 

We have an interface for IProjectSettingsResolver which returns the project settings which is then used to tag pages and posts with the projectid. The idea would be to only have one actual project settings per tenant but the instance returned can when needed append the -langcode to the siteid string that is the projectid. Then content would be saved with language specific projectids.

We've already come up with a solution for setting the thread culture based on the first folder segment as long as the segment corresponds to one of the supported cultures. For the default culture we don't need the segment. So instead of /fr corresponding to a folder tenant, it can just be a route segment that sets the culture and the culture when not the default culture can be used as part of the projectid. This solution would work for hostname tenants to have projectid per supported language.
We also came up with a way to do that for folder tenants so if I have a folder tenant at /joe it would be possible to have /joe/fr for French translation.

The remaining pieces of this are to support the additional routes in simplecontent and to implement the IProjectResolver to provide the language specific project id for cloudscribe core tenants. At least that is the theory, now we have to implement it and verify it can work and no detail that prevents it has been overlooked.

The other thing to consider is that "suppported languages" are defined in startup so they are global to the installation not defined per tenant. So any tenant could translate to any supported language, but no tenant has the option for languages that are not available also for other tenants. cloudscribe core tenants also have site settings to force a specific culture. That setting would take precedence over url segments. So for those who want to support more than one language per tenants you should never set a forced culture.

**Comment by joeaudette** [comment]
## Update

Where I originally thought we would only fake a project per language and just use an ammended projectid, I've decided to actually persist the project setting per language because there are project settings that should be different per language such as the "About" content which one would want to translate and also the feed settings have language setting that is used in the rss feed.

**Comment by joeaudette** [comment]
fyi @abomadi this work is now completed and I've published new nugets.

Now I just need to do some work in the project template so it can setup the new routing and localization settings and put new settings in appsettings that will be used to enable it.

     "ContentLocalizationOptions": {
    "UseCultureProjectIds": true,
    "UseCultureRoutes": true
  },

Those two settings will be false by default so you have to opt into using per language projects. And of course you have to configure the supported cultures in the /Config/Localization.cs

And the supported cultures really should always be full cultures like en-US fr-FR not en or fr, but the url segment can be the 2 character version ie /fr /ar /it etc. and it will work for both hostname tenancy and folder tenancy.

I also have to tweak the themes in the project template so it can resolve the correct url for the home page for the site title link and site logo link. I will do that with partial views.

**Comment by abomadi** [comment]
@joeaudette Thanks, i will give it a try

**Comment by joeaudette** [comment]
@abomadi not easy to test yet. I'm working on the project template updates now then it will be easy to test. In addition to the appsettings there are bunch of routes that have to be added. And the site title and logo links need different logic so the keep the culture segment. I'll post again once I ship the updated template, then it will be easy to try it.

**Comment by joeaudette** [comment]
This is completed and the project template has been updated.

To use the new localization approach for SimpleContent, you just configure suppported cultures:

    var supportedCultures = new[]
    {
	    new CultureInfo("en-US"),
	    new CultureInfo("it-IT"),
	    new CultureInfo("fr-FR"),
	    new CultureInfo("cy-GB"),
    };


    var routeSegmentLocalizationProvider = new UrlSegmentRequestCultureProvider(supportedCultures.ToList());

    services.Configure<RequestLocalizationOptions>(options =>
    {

	    options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
	    options.SupportedCultures = supportedCultures;
	    options.SupportedUICultures = supportedCultures;

	    options.RequestCultureProviders.Clear();
	    options.RequestCultureProviders.Insert(0, routeSegmentLocalizationProvider);

        });

and set this appsetting to true

    "ContentLocalizationOptions": {
        "UseCultureRoutesAndProjects": false
     },

now when on your home page just add /it to the url and you will see that the home page is not found and you are prompted to create it, this will be the Italian home page. And so on for other languages you want to support.

However, this only localizes cloudscribe SimpleContent, it does not localize cloudscribe Core. Therefore for most cases where your installation is not a saas offering, you are still better off to use folder tenants to represent the language. That way you can also localize cloudscribe Core things such as registration agreement, privacy policy, etc etc. Or you can use hostname tenants like it.somedomain.com, fr.somedomain.com etc, optionally using related sites mode to share users and roles across sites.
What you can't do today in cloudscribe Core is selectively relate sites so that some sites share users and roles but other sites are independent or have a different related site. That is something that could possibly be changed in a future version of cloudscribe core.

**Comment by joeaudette** [comment]
note also that to use this new feature in existing installations requires adding additional routes. Best to create a new project that has the needed routes and compare to your existing project.
