### ISSUE TITLE
How remove a page from all menus

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#424]
The "Menu Filters" help say to leave blank to include in all menus, or enter one or more of topnav, breadcrumbs, childtree. What if we don't want a page appearing in any?

As it happens I can enter "childtree", and since I don't have one of those on the parent page, this achieves the desired effect. But just wondering what the best approach should be? I'm thinking that entering any string that doesn't match a menu name would hide it, like "none", and in my testing this does work, but that's a bit subtle if not mentioned in the help popup.

**Comment by joeaudette** [comment]
Yes, the way to exclude a page from all menus is to use a non existent view name like "none". I've updated the help to indicate that and published a new nuget for the views.
