### ISSUE TITLE
Suggested Improvement to Blog Image Float CSS

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe.SimpleContent#426]
Hey Joe, using you awesome templates! And noticed the float images could be improved a little.

When we have a float image section, if the image is a little small the text isn't wrapping around the image and we're getting a lot of white space.

----

![image](https://user-images.githubusercontent.com/14014749/55429847-50bb3180-5584-11e9-9279-685b1f9c4ae8.png)

-----

I had a quick look at the CSS and we have a CSS class 'simple-side-image' which sets the image width to 690px.

I think a better class would just be to replace the 'simple-side-image' class with something like 'col-8' or 'col-7' and bootstrap css can resize. Also because I have some small images I'm stretching them using the `w-100` class additionally on the img class like this.

`<img class="image-responsive w-100" src="/media/images/barn-conversion-interior-2.jpg">`

**Comment by joeaudette** [comment]
Hi Hefin,

I don't think that using col class there would be correct usage of boostrap. Maybe try changing from width to max-width would solve it. Could you try that overriding in local css and let me know?

Thanks,

Joe

**Comment by hsankala** [comment]
Yep, wraps the text around nicely with max-width

![image](https://user-images.githubusercontent.com/14014749/55431179-c674cc80-5587-11e9-9499-956f25669ba7.png)

**Comment by joeaudette** [comment]
Thanks! I'll change that and ship a new nuget tomorrow. Busy installing VS 2019 right now!

**Comment by hsankala** [comment]
Oh it's the launch event right now! Enjoy.

**Comment by joeaudette** [comment]
went ahead and fixed it since it is a trivial fix, new nuget published https://www.nuget.org/packages/cloudscribe.SimpleContent.ContentTemplates.Bootstrap4/1.0.18
