### ISSUE TITLE
Cannot change publication date/time for a post that is already published

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#429]
How to reproduce:
1. Create a blog post and "Publish Now".
2. Edit the post and change the date (past or future) and hit "Publish at Date/Time".
3. Makes no difference - the change is lost. Nothing in System Log.

**Comment by joeaudette** [comment]
Thanks for the bug report. This problem seems to have been introduced by #422, the changes implemented for that missed some nuance of the logic, and wasn't quite correct. 

I've fixed it and published an updated nuget: https://www.nuget.org/packages/cloudscribe.SimpleContent.Web/4.0.35
