### ISSUE TITLE
PageScriptsPartial, StylePartial,  BlogStylePartial, and BlogScriptsPartial Pulling in highlight pack css/js by default

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe.SimpleContent#433]
Hey up Joe.  I was slimming down my CS site removing any possible non-essential JS/CSS calls to try and get a better pagespeed score with google.

I noticed that this JS and CSS coming down:

```
<script src="~/cr/js/ckeditor461/plugins/codesnippet/lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

It appears the call is coming from the ScriptsPartial.cshtml view, I simply overridded the view and removed the refereres as I didn't need them [highlight.pack.js](https://github.com/cloudscribe/cloudscribe.SimpleContent/search?q=%2Fcr%2Fjs%2Fckeditor461%2Fplugins%2Fcodesnippet%2Flib%2Fhighlight%2Fhighlight.pack.js&unscoped_q=%2Fcr%2Fjs%2Fckeditor461%2Fplugins%2Fcodesnippet%2Flib%2Fhighlight%2Fhighlight.pack.js) and some [highlighter styles](https://github.com/cloudscribe/cloudscribe.SimpleContent/search?q=%2Flib%2Fhighlight%2Fstyles&unscoped_q=%2Flib%2Fhighlight%2Fstyles)

But I noticed in your documentation page [customizing-the-editor](https://www.cloudscribe.com/customizing-the-editor) it suggests that these could be added by the developer rather already being there by default.

So just raising this issue as a double check,  just in case you intended on removing them.

**Comment by joeaudette** [comment]
Thanks Hefin, the document was out of date, I've updated the document to indicate that we are including that by default.

**Comment by hsankala** [comment]
Sure thing.
