### ISSUE TITLE
SimpleContent requires sitefiles folder even when UseSharedThemes = true

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe.SimpleContent#437]
In my application all my tenants using the same theme. I put this in `appsettings.json`:
`    "UserPerSiteThemes": "false",
    "UseSharedThemes": "true"`
and I decided to delete `sitefiles ` directory. Main reason to delete that I will not use it and I have to ignore it every time during synchronization etc.

But in this case site fails with `System.IO.DirectoryNotFoundException: 'C:\Projects\Blog\New\Blog\sitefiles\s1\themes\custom1\wwwroot\'` and not rendering at all.

Steps to reproduce. Create new site using this:
`dotnet new cloudscribe -D NoDb -S a -L true`

move custom1 theme from `sitefiles\s1\themes` to `SharedThemes`, delete/rename `sitefiles` directory and apply changes to `appsettings.json`:
`    "UserPerSiteThemes": "false",
    "UseSharedThemes": "true"`
and run app. You will see .Net Core screen of death. 

I understand that this is low priority but I spent few hours trying to understand why it doesn't work because I knew that  `sitefiles` directory not suppose to be used all.

**Comment by joeaudette** [comment]
There are differences in _Layout file for shared themes vs non shared themes so just moving the theme is not sufficient, see the notes in the docs about the differences. https://www.cloudscribe.com/themes-and-web-design.

**Comment by joeaudette** [comment]
Also note custom1 is a special theme, the css is generated from sass files so if you move it you need to edit gulp file to correct the path.

**Comment by cheverdyukv** [comment]
Ok assume that instead of custom1 from sitefiles I just changed theme for s1 tenant to superhero

**Comment by cheverdyukv** [comment]
Just to clarify, problem is not with theme itself but that `sitefiles\s1\themes` should exist when I use shared themes or else I got Internal Server Error.

**Comment by cheverdyukv** [comment]
Sorry I think I understand what you mean. Let me check it

**Comment by cheverdyukv** [comment]
Thank you it works correctly but content of https://www.cloudscribe.com/themes-and-web-design is outdated. There much heavier differences between shared and non shared themes than described in document. For example one uses site.css another uses style.css.
