### ISSUE TITLE
Link List content template: allow alt of image to be set individually, as the description may not be suitable

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#460]
The description of the link may not be appropriate for the description of the image, and it may also be too long triggering accessibility alerts.
Allow this to be (optionally) entered individually for each link item.

**Comment by CrispinF** [comment]
Could we push this through within a couple of weeks now, as needed for a client project (accessibility checks picked this issue up).

**Comment by JimKerslake** [comment]
This was pushed to nuget.org as v3.0.3 of cloudscribe.SimpleContent.ContentTemplates.Bootstrap4

**Comment by JimKerslake** [comment]
Tested that attempts to inject unsafe characters via this field result in safely encoded alt values in rendered html.
