### ISSUE TITLE
Typo in content version history

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#476]
"A previous verion of this page has been restored to the editor".
Also the texts suggest you "click cancel" to abort, when no such button exists. We can re-work these messages slightly.

**Comment by CrispinF** [comment]
Partial views updated

**Comment by JimKerslake** [comment]
Pushed new packages to nuget.org at v.5.0.1

**Comment by CrispinF** [comment]
Actually, revisiting this, I see there IS a Cancel link!   However, it's not with the other buttons, at the bottom of the post, it's at the top next to the page name. Everyone I've given basic CMS training to finds this confusing, so I'm going to raise a new issue to look at why it's there and whether it could be moved next to the other action buttons.  
I don't think the text changes made above need to be reversed, but we can review in due course.
