### ISSUE TITLE
Page/Post "Cancel" link - can this be positioned with the other action buttons

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#483]
Best would be to left of "Save Draft", using appropriate button style.

**Comment by JimKerslake** [comment]
Yes it can :)

**Comment by JimKerslake** [comment]
Only committing this change for the Bootstrap4 views at the moment - 
although it seems a pretty innocuous change, I failed to get the dev web app running cleanly with the Bootstrap3 views, and so could not preview & test the change with them.

**Comment by JimKerslake** [comment]
Took me a while to realise that there are separate editing views for templated pages, which also needed the same treatment.  Pushed a second version increment.

**Comment by CrispinF** [comment]
Tested in a newly deployed site - much better!  What about BS3?

**Comment by JimKerslake** [comment]
Tried one more time to take a fresh VSIX template site and flip it back to using the BS3 views by downgrading the various NuGet references: 

- cloudscribe.Core.SimpleContent.CompiledViews.Bootstrap3
- cloudscribe.SimpleContent.CompiledViews.Bootstrap3
- cloudscribe.Core.CompiledViews.Bootstrap3

but still got a tangle of missing partial views...  feels like the _layout files in the site themes are referencing view components / partial views that are only present in the BS4 libraries...?

When it comes to the content templates, there only is a BS4 library, no BS3:
cloudscribe.SimpleContent.ContentTemplates.Bootstrap4
(does that mean content templates are not supported in BS3?)

So I failed to get myself to a working BS3 test site... not sure if worth the time of persisting.

**Comment by CrispinF** [comment]
@joeaudette thoughts on whether we should attempt to maintain support for BS3? 
We're thinking we should probably now drop this support and say so in https://github.com/cloudscribe/Announcements if you agree?

**Comment by joeaudette** [comment]
Dropping bs3 is fine with me.
