### ISSUE TITLE
Blog: add option to show/hide Categories and Archives in sidebar

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#488]
And if neither of these or Related Posts or the About box is shown, blog list/detail can be full-width.
While doing this it would be useful to add ids to the various containers.

**Comment by CrispinF** [comment]
These should be two separate options. In Content Settings, two new checkboxes for 
Show Archive in the blog side bar
Show Categories in the blog side bar

**Comment by markidox** [comment]
PR: https://github.com/cloudscribe/cloudscribe.SimpleContent/pull/603
To test: turn display options on/off in the Content Settings to see them show/not show in the right hand panel on a blog page. All must be turned off for the right hand panel to completely vanish and the content stretch into the space.

**Comment by CrispinF** [comment]
@markidox I've deployed this to an existing site where I'm certain the categories and archives were previously displaying, and now they are not displaying. The new checkboxes in /contentsettings are false.
Where possible we should not alter the behaviour of existing sites when adding new features. If these are new database fields, the default values should be true, to preserve previous functionality.
