### ISSUE TITLE
Publishing images within an Open Live Writer post fails

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#491]
See https://www.cloudscribe.com/forum/thread/is-ftp-access-possible-with-open-live-writer

I tested posting with an image in the post and got this result:
![image](https://user-images.githubusercontent.com/10574730/75294969-99757c00-5821-11ea-87e4-2ee19908154b.png)

**Comment by CrispinF** [comment]
To check whether this failure was caused by a lack of permissions, in a test site I gave the application pool identity modify rights on the website root folder, and on posting an image from OLW the same error was raised:
![image](https://user-images.githubusercontent.com/10574730/75333839-be4c0c80-587e-11ea-9221-14d1d5219501.png)
So it's not just permissions.

**Comment by CrispinF** [comment]
Exception is
`{"Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead."}	System.Exception {System.InvalidOperationException}`
Seemingly caused by one of the breaking changes listed here https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0 specifically "HTTP: Synchronous IO disabled in all servers". 
I've improved the logging to write the exception message to the log rather than oops, and change the method of reading the posted xml.

**Comment by JimKerslake** [comment]
cs.MetaWebLog nuget version needs to be bumped, but other projects referencing it also need an increment, else this fix will not find its way out into the world via the VS template.

Includes 
cs.SimpleContent.MetaWeblog
cs.Core.SimpleContent
and potentially other things that reference them.

**Comment by JimKerslake** [comment]
Pushed what I think to be a minimal set of new nugets as:
cs.MetaWebLog v3.0.3
cs.Core.SimpleContent  v5.0.3
cs.SimpleContent.MetaWeblog   v5.0.3

Needs a test that I didn't miss anything.
I do see that 
cloudscribe.Core.SimpleContent.CompiledViews.Bootstrap3
cloudscribe.Core.SimpleContent.CompiledViews.Bootstrap4
depend on cloudscribe.Core.SimpleContent
but I didn't bump those, since the template references cloudscribe.Core.SimpleContent directly.

**Comment by JimKerslake** [comment]
@CrispinF  If this tests OK, could you please delete this feature branch when closing ticket?

**Comment by CrispinF** [comment]
Tested OK in a production site in IIS.
