### ISSUE TITLE
Deleting a blog post with comments fails

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#504]
Using TalkAbout Comments, deleting a blog post with comments fails to delete the post. This in System Log:
System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_cs_PostComment_cs_Post_PostEntityId". The conflict occurred in database "xxxx", table "dbo.cs_PostComment", column 'PostEntityId'.
This was in SQL Server. Not tested in other storage options yet.

**Comment by CrispinF** [comment]
Also fails in pgsql.
Npgsql.PostgresException (0x80004005): 23503: update or delete on table "cs_post" violates foreign key constraint "fk_cs_post_comment_cs_post_post_entity_id" on table "cs_post_comment"

**Comment by CrispinF** [comment]
@JimKerslake probably three options here: 

1. Delete comments before deleting post
2. Remove FK and leave orphan comments
3. Change the FK to do a cascade delete, and leave code unchanged

Option 2 doesn't seem sensible. 
@joeaudette is there a standard pattern to follow?

**Comment by joeaudette** [comment]
I would delete the comments before deleting the post.

**Comment by JimKerslake** [comment]
Code already was deleting comments before deleting the post itself... but was passing a 'false' boolean to the command that prevented committing that change to the Db.  Couldn't work out what the intention of that boolean was - but flipped it the other way.  Pushed new packages at 5.1.3   cs.SimpleContent.Storage.EFCore.(all)
