### ISSUE TITLE
Allow editor to abandon draft page/post content

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#508]
If as a page editor you Save Draft content, then make a mess of it somehow, it's not easy to recover. There's no way to abandon the draft, and the only options are 
a) publish the draft then edit again and use Version History to recover the last good version, or 
b) try to copy good content back into the editor.

I can see two possible ways of allowing a user to abandon a draft in the UI:
Option 1: add a new button "Delete Draft" between these two buttons:
![image](https://user-images.githubusercontent.com/10574730/83419387-e4a0bb80-a41c-11ea-8869-38773fc178e2.png)
Option 2: make the Delete button delete the Draft when in this mode, rather than the Page as it does now.

The same applies when editing a blog post.

**Comment by JimKerslake** [comment]
It is already possible to abandon a draft in this way (without ever having published it) 
but it is very non-intuitive, so will look to introduce a more explicit button.

For reference - at present - the way of achieving this is:
a) edit the page and go to its content history
b) load the last good version that you want to revert to (that can be either a published version or the last 'good' draft in the stored history) into the editor 
c) save that version as a **draft**
d) in the page history, your previous 'bad' draft is then listed as the last (topmost) history item - from where it can be viewed and  deleted
e) all the while, the current published version remains unaffected by any of this


Anyhow - testing implies that we can just null out the various Draft fields in the current main Db table row without getting the history into an inconsistent / broken state.
