### ISSUE TITLE
Blog Menu Position behaves strangely

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#513]
In a Simple Content site I'm seeing very odd behaviour and cannot position the Blog where I want it.

if I have these page orders set
Page1  10
Page2  15
Blog     20
I get this menu:
Other pages... Page1 Blog Page2

and if I change the ordering to this
Page1  30
Page2  15
Blog     20
I get this menu
Other pages...  Page2 Blog Page1

What!??

Multi-tenant site with hostname mode. The above is observed in s2.

**Comment by JimKerslake** [comment]
@CrispinF 

I **think** that it is a mistake to assume that those two numbers have the same meaning.

So far as I can tell...
The page order integer sets the relative precedence of pages to one another (and can affect their ordering within a drop-down menu) - but I think it's just a relative rank (i.e. you can use 15 and 30 as above).

The blog menu position is an absolute integer that will attempt to set the position of the blog link in the menu, counting 1-based from the left (which may or may not include a 'Home' link).  If you spin up the simplecontent solution you can see that setting it to 4 does set it to be the 4th item in the nav menu (counting from 'Home').  It doesn't care if it is surrounded by links to pages whose page order might be set to 15, 30... just so long as it is the 4th item.

The simplecontent navigation tree builder cannot (at this point) ever know about other stuff that might be getting added to the menu later by other components, (eg 'Forum' or 'Administration') so I am guessing that the furthest to the right the Blog can ever be, is after the final content document link.  If you set  blog menu position to 999 it gets re-set in code to make it the last item after the page nav-links.

Except that here is a bug in that last aspect - it's off by 1 such that it can never quite get to the right of the very last page nav-link.  So at the moment the best you can ever achieve is anywhere between

Home | Blog | page1 | page2 | page3 | ... | pageN | Other stuff | Admin
and
Home | page1 | page2 | page3 | ... | pageN-1 |  Blog | pageN | Other stuff | Admin

I'll see if I can fix that off-by-1 issue.

**Comment by JimKerslake** [comment]
PS - so in your examples above, blog menu position was set to 20 - way over the total number of menu links - 
so was always trying to be the last item after all the page links - and ending up as the penultimate one because of the bug.

**Comment by JimKerslake** [comment]
@CrispinF   Note that all the above only works at all if  you have CS simplecontent set up with the first vsix template option - to allow simplecontent to provide the 'Home' route from a content page.  

In this mode you can then add additional content pages and have them span out as main menu links.  And you can position your Blog node within them

If you select the non-default option of having Home provided by a Home controller, then simplecontent pages just sit within a single 'Articles' main menu item, and I can't see a way of getting any additional content pages into the main menu from there - (there might be a way and I'm just missing it?)  -  and the blog positioning value is just ignored.  
In fact in this second case the vsix template delivers the site with a config setting set to prevent the editor box for that Blog menu position value being displayed at all... perhaps for this reason.

**Comment by JimKerslake** [comment]
PS - in that second configuration (Home provided by a Home controller) the option 'Add Blog To Menu' is also odd, because it adds Blog to the chosen position of the drop-down pages menu underneath 'Articles'.  This option is also hidden my default in that configuration.

**Comment by JimKerslake** [comment]
candidate fix cloudscribe.SimpleContent.Web 5.1.5
