### ISSUE TITLE
Version History - the View button should not open a new window/tab

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#517]
`<a class="btn btn-primary btn-sm" href="/home?historyId=9589587e-64aa-40ec-bbaf-f036b99fd36a" target="_blank" title="opens in a new window">View</a>`
remove the target="_blank" title="opens in a new window".
Users can open links in new windows/tabs if they want to.

**Comment by JimKerslake** [comment]
done 
cloudscribe.SimpleContent.CompiledViews.Bootstrap4  5.1.6
