### ISSUE TITLE
Page heading is rendered as H2 if choose "No Content Only Show Child Menu"

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#524]
I'm observing this is a site using a fairly old version of SimpleContent, 4.0.41 so possibly it's already been changed (but I don't recall it).
With this setting enabled, the page heading is rendered in an H2 e.g.
`<h2>My page</h2>`
Without this setting, it is H1 e.g.
`<h1 id="article-title" itemprop="headline name">My page</h1>`
Presumably this was done deliberately (the result also omits other mark-up associated with an "article"), but I think the title should still be H1.

**Comment by JimKerslake** [comment]
done
cloudscribe.SimpleContent.CompiledViews.Bootstrap4  5.1.6
