### ISSUE TITLE
Bootstrap5: Broken content template layout

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe.SimpleContent#545]
Simple image gallery with optional content above and below
when using the option  Gallery >> Layout >> Compact 
the image titles etc migrate to the very bottom of the page (overspilling the footer).

The positioning of those titles is attempting to be set via absolute positioning:
position: absolute;
bottom: 0;
left: 0;

So perhaps in BS5 that absolute positioning is getting interpreted as absolute within the page itself, rather than absolute within only the container div for the image.,,?

**Comment by markidox** [comment]
Fix released for Layout view.
