### ISSUE TITLE
Page/post settings "View Roles" control and button layout

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#569]
This is how they are now:
![image](https://user-images.githubusercontent.com/10574730/233331608-4473d200-7f56-458f-b707-fbe597be7676.png)

I think at some point in the distant past the button was to the right of the control (which is not full-width). Try restoring that, dropping below on narrow screens.
And if/when the button needs to be below the control, add some vertical spacing.

**Comment by markidox** [comment]
duplicate of #597
