### ISSUE TITLE
Add content template to allow differential content for un-/authenticated users 

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe.SimpleContent#578]

**Comment by JimKerslake** [comment]
This should now be delivered as a new available content template when creating a new simplecontent page:

**Role based content
Render different content depending on whether the user is authenticated, unauthenticated, or in a particular role**

The template delivers 3 content editors:
- content to be seen by unauthenticated users
- content to be seen by authenticated users  (replaces the above for an authenticated user)
- content to be seen by users in any of the specified roles:   a CSV listing of applicable roles should then be supplied.

By default, the third, Role based content will be displayed **beneath** the authenticated content, if the user is in one of the specified roles. However there is a checkbox that changes that behaviour such that the Role-specific content **replaces** the authenticated content fully.

**Comment by JimKerslake** [comment]
cloudscribe.SimpleContent.ContentTemplates.Bootstrap5  at v 6.0.4

**Comment by CrispinF** [comment]
Documentation updated here https://www.cloudscribe.com/content-templates
