### ISSUE TITLE
Edit menu has disappeared for blog posts

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#605]
Following #486 I see the new page editing menu in a site, but on a blog post I have no editing tools.

**Comment by CrispinF** [comment]
Aha - I've found the tools - they are centred below the footer. This markup:

![Image](https://github.com/user-attachments/assets/bb670446-1af6-4368-a67e-b63ad89c23f8)

**Comment by markidox** [comment]
This has now been resolved. The styling will match what users see with the page editing details.
